FROM prom/prometheus:latest
COPY prometheus /etc/prometheus
CMD ["--config.file=/etc/prometheus/prometheus.yml",\
"--storage.tsdb.path=/prometheus",\
"--web.console.libraries=/etc/prometheus/console_libraries",\
"--web.console.templates=/etc/prometheus/consoles",\
"--storage.tsdb.retention.time=600h",\
"--web.enable-lifecycle",\
"--web.listen-address=127.0.0.1:9090"]
